### PR TITLE
Make ``__init__`` better

### PR DESCRIPTION
**Pull request by RPSMain**

### CODE REVIEW

**Review by vveeps — COMMENTED** [review]
lowercase w and maybe separate year and author with a comma :) cool change tho, thanks

**Comment by cloudwithax** [comment]
Change the description to the one on the repo and you got yourself a deal

**Comment by RPSMain** [comment]
> Change the description to the one on the repo and you got yourself a deal

Should be changed now

**Comment by cloudwithax** [comment]
Awesome, merging now

**Pull request merged**
