### PR TITLE
Add sphinx_rtd_theme theme for docs

### PR DESCRIPTION
**Pull request by DeadPool3333**
New theme for this documentation looks good to read the methods and objects.

### CODE REVIEW

**Comment by DeadPool3333** [comment]
Hello, can anyone please review this PR?

**Comment by ooliver1** [comment]
docs/_build should not be stored right?

**Comment by DeadPool3333** [comment]
Idk to store that directory or not i just check he previous files https://github.com/cloudwithax/pomice/tree/main/docs/_build and added them and committed.

**Comment by Aspect1103** [comment]
_build isn't needed. It's just used as a test directory so you can see what the documentation looks like on your machine first before having readthedocs build it.

**Comment by cloudwithax** [comment]
Yes, please make sure that when you push your changes that you don't include any unnecessary files.

**Comment by DeadPool3333** [comment]
Ok lemme do that.

**Comment by DeadPool3333** [comment]
Ok so i remove `docs/_build` directory.

**Comment by DeadPool3333** [comment]
> Just delete the build dir and gitignore it, it's a pain to review if it's got a bjillion edited files

I have a small doubt, `docs/_build` is already in `.gitignore` then why it updated that directory?

**Comment by ooliver1** [comment]
It was probably already there so git decided to track it instead or something

**Comment by DeadPool3333** [comment]
Oh ok thanks.

**Comment by DeadPool3333** [comment]
Hey whats the status about this PR?

**Pull request merged**
