### PR TITLE
update player.py, utils.py

### PR DESCRIPTION
**Pull request by Crussader**

### CODE REVIEW

**Comment by cloudwithax** [comment]
Can you please describethe changes/improvements you made here?

**Comment by Crussader** [comment]
yea what you had is like a default player

**Comment by Crussader** [comment]
> first of all update your fork, events got a rewrite today
> 
> secondly, dont break Player - just add `__call__` so `VoiceChannel.connect` can call the instance and do whatever instantiating would

if you did a re-write today thats not gonna be an be big problem since the only thing i changed is the if statements thats all

**Comment by cloudwithax** [comment]
This PR has been closed, have a great day.

**Comment by vveeps** [comment]
type client as `utils.ClientType` and channel as `discord.VoiceChannel`, theyre both already imported

leave the MISSING stuff for later, i was thinking of that earlier today while dealing with other typing related things

**Pull request closed without merging**
