### PR TITLE
Internal re-write of Spotify Client

### PR DESCRIPTION
**Pull request by Crussader**
# Summary

Spotify Client Re-written to make it faster. It may not look that different from the previous one but the speed differences is significant.

There is no breaking change since i haven't changed any existing functions, it has been internally re-written.

- This also supports Spotify Artists 

# Performance Difference

The following test was done with this [Spotify Playlist](https://open.spotify.com/playlist/6yPiKpy7evrwvZodByKvM9) and it consists of 10,000 Tracks

|Test No.  | Old `client.py`| New `client.py`|
|--------- | -------------- | --------------- |
|1.| `37.6127` | `1.2377` |
|2.| `29.4823`| `1.7683`|
|3.| `29.5969`|`1.6120 `|
|4.| `29.8474`| `1.5434`|
|5.| `29.9379`| `1.5819`|

Old `client.py`: avg. 31.2948 secs.
New `client.py`: avg. 1.5482 secs.

Therefore there is an increase of `95.05 %`

# Caveat

There is a caveat for this speed, though it can do back to back without getting rate limited, there is a chance you could temporarily rate limited.

But do note this is a Playlist that practically no one would use other than *testing purposes*, so you shouldn't get rate limited.

### CODE REVIEW

**Comment by cloudwithax** [comment]
Please resolve any conflicts with the recent push before I submit.

**Comment by Crussader** [comment]
Conflicts have been fixed, and cleaned code in `client.py`

**Comment by ilkergzlkkr** [comment]
Does this pr still draft after the "Revert 1.1.8 spotify removal" 3687f9b33ac187f74c69c4839696b6add6eff82f ?
@cloudwithax @Crussader

**Comment by Crussader** [comment]
> Does this pr still draft after the "Revert 1.1.8 spotify removal" 3687f9b33ac187f74c69c4839696b6add6eff82f ?
> 
> @cloudwithax @Crussader 

Well this should work, but I need to check there might be some differences, after-all I stopped maintaining this cuz it wasn't checked upon after the conflicts got resolved then and there

**Comment by NiceAesth** [comment]
would you still be open to working on this PR? (also, for the rate limiting issue we could use a leaky bucket ratelimiter to make sure we don't exceed them)

**Comment by cloudwithax** [comment]
closing this since this has been left stale for over a year

**Pull request closed without merging**
